services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    environment:
      SA_PASSWORD: Asd1234.
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/lib/mssqlql/data

volumes:
  db_data:

