services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backups:/var/backups/database_backups

networks:
  my-app-network:
    driver: bridge

volumes:
  db_data:

