
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB= root
      - POSTGRES_USER= root
      - POSTGRES_PASSWORD= root
    ports:
      - "5432:5432"
    volumes:
     - db_data:/var/lib/postgresql/data
volumes:
  db_data: 
